export const NAV = {
  patient: [
    { to: "/patient/dashboard", label: "Dashboard", icon: "Home" },
    { to: "/patient/find-doctor", label: "Find Doctor", icon: "Search" },
    { to: "/patient/appointments", label: "My Appointments", icon: "Calendar" },
    { to: "/patient/online-consultation", label: "Online Consultation", icon: "Video" },
    { to: "/patient/prescriptions", label: "Prescriptions", icon: "FileText" },
    { to: "/patient/medicines", label: "Pharmacy / Medicines", icon: "Pill" },
    { to: "/patient/health-record", label: "Health Records", icon: "Activity" },
    { to: "/patient/referrals", label: "Referrals", icon: "Share" },
    { to: "/patient/emergency-help", label: "Emergency Help", icon: "AlertCircle" },
    { to: "/patient/notifications", label: "Notifications", icon: "Bell" },
    { action: "logout", label: "Logout", icon: "LogOut" },
  ],
  healthworker: [
    { to: "/healthworker/dashboard", label: "Dashboard", icon: "Home" },
    { to: "/healthworker/todays-tasks", label: "Today's Tasks", icon: "CheckSquare" },
    { to: "/healthworker/emergency-cases", label: "Emergency / Critical Cases", icon: "AlertCircle" },
    { to: "/healthworker/patient-visits", label: "Patient Visits", icon: "Users" },
    { to: "/healthworker/my-patients", label: "My Patients", icon: "Users" },
    { to: "/healthworker/register-patient", label: "Register Patient", icon: "UserPlus" },
    { to: "/healthworker/health-assessment", label: "Patient Assessment", icon: "Activity" },
    { to: "/healthworker/doctor-consultation", label: "Doctor Consultation", icon: "Stethoscope" },
    { to: "/healthworker/referrals", label: "Referrals", icon: "Share" },
    { to: "/healthworker/follow-ups", label: "Follow-ups", icon: "Clock" },
    { to: "/healthworker/high-risk-patients", label: "High-Risk Patients", icon: "ShieldAlert" },
    { to: "/healthworker/notifications", label: "Notifications", icon: "Bell" },
    { action: "logout", label: "Logout", icon: "LogOut" },
  ],
  doctor: [
    { to: "/doctor/dashboard", label: "Dashboard", icon: "Home" },
    { to: "/doctor/patient-requests", label: "Patient Requests", icon: "ClipboardList" },
    { to: "/doctor/appointments", label: "Appointments", icon: "Calendar" },
    { to: "/doctor/my-patients", label: "My Patients", icon: "Users" },
    { to: "/doctor/consultations", label: "Consultation", icon: "Video" },
    { to: "/doctor/prescriptions", label: "Prescription", icon: "FileText" },
    { to: "/doctor/refer-patient", label: "Referral", icon: "Share" },
    { to: "/doctor/follow-ups", label: "Follow-up", icon: "Clock" },
    { to: "/doctor/notifications", label: "Notifications", icon: "Bell" },
    { action: "logout", label: "Logout", icon: "LogOut" },
  ],
  pharmacy: [
    { to: "/pharmacy/dashboard", label: "Dashboard", icon: "Home" },
    { to: "/pharmacy/prescription-requests", label: "Prescription Requests", icon: "FileText" },
    { to: "/pharmacy/notifications", label: "Notifications", icon: "Bell" },
    { action: "logout", label: "Logout", icon: "LogOut" },
  ],
  admin: [
    { to: "/admin/command-center", label: "Dashboard Overview", icon: "Home" },
    { to: "/admin/patients", label: "Patient Management", icon: "Users" },
    { to: "/admin/doctor-management", label: "Doctor Management", icon: "Stethoscope" },
    { to: "/admin/pharmacy-management", label: "Pharmacy Management", icon: "Building" },
    { to: "/admin/appointment-management", label: "Appointment Management", icon: "Calendar" },
    { to: "/admin/care-team", label: "Care Team", icon: "HeartPulse" },
    { to: "/admin/emergency-referrals", label: "Emergency Referrals", icon: "AlertCircle" },
    { to: "/admin/resource-monitoring", label: "Resource Monitoring", icon: "Box" },
    { to: "/admin/follow-ups", label: "Follow-ups", icon: "Clock" },
    { to: "/admin/medicines", label: "Medicines", icon: "Pill" },
    { to: "/admin/alerts", label: "Alerts", icon: "Bell" },
    { to: "/admin/reports", label: "Reports", icon: "BarChart" },
    { to: "/admin/impact-analytics", label: "Impact Analytics", icon: "TrendingUp" },
    { to: "/admin/notifications", label: "Notifications", icon: "Bell" },
    { action: "logout", label: "Logout", icon: "LogOut" },
  ],
};

export const ROLE_LABEL = {
  patient: "Patient",
  healthworker: "ASHA / Health Worker",
  doctor: "Doctor",
  pharmacy: "Pharmacy",
  admin: "District Admin",
};
